[project]
name = "discord-ai-agent"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord>=2.3.2",
    "fire>=0.7.0",
    "mcp>=1.6.0",
    "ogbujipt>=0.9.6",
    "rich>=14.0.0",
    "structlog>=25.2.0",
]

[tool.poetry.dependencies]  # Uses new PEP 508 format. Pulling from GitHub because package is not yet on PyPI
mcp-sse-client = "https://github.com/zanetworker/mcp-sse-client-python.git#f397a8e"
