[b4a] # Config for e.g. tools & resources, including via MCP

source_sets = [
  "toys.b4a.toml",
  "news.b4a.toml",
  # "gdrive_mcp.b4a.toml",
]

[llm_endpoint]
# Local LLM via LM Studio
# API type: "generic" (default, OpenAI-compatible), "openai" (OpenAI cloud), "claude" (Anthropic Claude)
api_type = "generic"
base_url = "http://localhost:1234/v1"

# Use this form if you're using LM Studio to run mlx-community/Qwen2.5-14B-Instruct-1M-4bit
# model = "qwen2.5-14b-instruct-1m"
# Or use this if you're running the same model with mlx_lm.server
model = "mlx-community/Qwen2.5-14B-Instruct-1M-4bit"

# Claude model - choose one of the following. Reference: https://docs.claude.com/en/docs/about-claude/models/overview
# api_type = "claude"
# model = "claude-sonnet-4-5-20250929"  # Latest and most capable
# model = "claude-haiku-4-5-20251001"  # Fastest and cheapest
# model = "claude-opus-4-1-20250805"   # Expensive & almost certainly overkill


# mlx-community/Llama-3.2-3B-Instruct-4bit is very small & efficient, but not great at reasoning for tool-calling
# model = "llama-3.2-3b-instruct"  # LM Studio form
# model = "mlx-community/Llama-3.2-3B-Instruct-4bit"  # mlx_lm.server form

# API keys should be provided via environment variables:
# - OPENAI_API_KEY for generic/openai providers
# - ANTHROPIC_API_KEY for claude provider

sysmsg = "You are a helpful AI assistant. When you need to use a tool, you MUST use the provided function-calling mechanism. Do NOT simply describe the tool call in your text response. The user's Discord ID is {DISCORD_ID}. The current date time/date is {CURRENT_TIME_DATE}. IMPORTANT: When asked to summarize or check RSS feeds, news, or any external data, you MUST use the query_rss_feed tool to get the actual data first. Do not make assumptions about what data might be available."
# sysmsg = "You are a helpful AI assistant running as a private, self-hosted LLM. When you need to use a tool, you MUST use the provided function-calling mechanism. Do NOT simply describe the tool call in your text response. The user's Discord ID is {DISCORD_ID}. The current date time/date is {CURRENT_TIME_DATE}. IMPORTANT: When asked to summarize or check RSS feeds, news, or any external data, you MUST use the query_rss_feed tool to get the actual data first. Do not make assumptions about what data might be available."

[model_params]
temperature = 0.3
max_tokens = 1000

[pgvector_history]
# Enable persistent chat history using PostgreSQL with PGVector extension
# When enabled, requires AIBOT_PG_* environment variables to be set (see README.md)
enabled = false
