# news.b4a.toml
# Describes a simple direct integration - an RSS feed data source.

[[context_source]]
type = "@rss"
name = "python_status"
description = "Python status updates"
url = "https://status.python.org/history.rss"

[[context_source]]
type = "@rss"
name = "Reddit r/LocalLLaMA"
description = "News from the LocalLLaMA subreddit, a community for allsorts of open-source LLM and GenAI models & tools."
url = "https://www.reddit.com/r/LocalLLaMA.rss"

# Optional configuration for the handler:
# refresh_interval = "1h" # Example: How often the agent should check for updates.
# max_items = 10 # Example: Limit the number of items processed.
