# Example configuration for Reddit RSS feeds using the new @rss.reddit type
# This file demonstrates how to configure Reddit-specific RSS feeds

[[context_source]]
name = "Reddit r/LocalLLaMA"
type = "@rss.reddit"
url = "https://www.reddit.com/r/LocalLLaMA.rss"
refresh_interval = "300"  # 5 minutes
max_items = 50
cosine_similarity_threshold = 0.7
top_k = 10

[[context_source]]
name = "Reddit r/MachineLearning"
type = "@rss.reddit"
url = "https://www.reddit.com/r/MachineLearning.rss"
refresh_interval = "600"  # 10 minutes
max_items = 30
cosine_similarity_threshold = 0.65
top_k = 5

[[context_source]]
name = "Reddit r/artificial"
type = "@rss.reddit"
url = "https://www.reddit.com/r/artificial.rss"
refresh_interval = "900"  # 15 minutes
max_items = 25

# Standard RSS feed for comparison
[[context_source]]
name = "TechCrunch"
type = "@rss"
url = "https://techcrunch.com/feed/"
refresh_interval = "1800"  # 30 minutes
max_items = 20 