# toy.example.b4a.toml
# Configuration for connecting to the toy MCP server using Streamable HTTP transport

[[context_source]]
name = "toy_server"
description = "Toy MCP server with basic tools for testing"
type = "@mcp" # REQUIRED: Specifies the integration handler type.

# Configuration specific to the '@mcp' handler:
connection_method = "streamable_http" # REQUIRED: Use Streamable HTTP transport
url = "http://localhost:8901/mcp/" # REQUIRED: Endpoint for the MCP Server (Streamable HTTP) 