# toys.b4a.toml
# Describes connecting to an MCP Server that provides a basket of silly demo tools
# Simple demo of delegating to MCP for tools loading

[[context_source]]
name = "mcp-toys"
description = "A basket of silly demo tools"
type = "@mcp" # REQUIRED: Specifies the integration handler type.

# Configuration specific to the '.mcp' handler:
connection_method = "http" # REQUIRED: How to communicate (e.g., 'http', 'stdio').
url = "http://localhost:8902/http" # REQUIRED: Endpoint for the MCP Server (HTTP example).
# Or for stdio:
# connection_method = "stdio"
# command = ["python", "path/to/mcp_server_script.py"]

# The toy servers do no auth
